server:
  port: 9090
  servlet:
    context-path: /

coolq:
  url: http://192.168.60.128:5700

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coolq?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#showSql
logging:
  level:
    com:
      example:
        coolq:
          mapper: debug