# Spring配置
spring:
  profiles:
    active: dev
  thymeleaf:
    check-template-location: false
# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.example.quartz.entity.**
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  # configLocation: classpath:mybatis/mybatis-config.xml
